# Generated by Django 4.2.16 on 2026-05-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'category', 'year', 'month'], name='budget_user_cat_ym_idx'),
        ),
    ]
